sudo: required
services: 
  - docker

before_install:
  - docker build -t nevhirion/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nevhirion/react-test npm test -- --coverage

after_success:
  - docker build -t nevhirion/multi-client ./client
  - docker build -t nevhirion/multi-nginx ./nginx
  - docker build -t nevhirion/multi-server ./server
  - docker build -t nevhirion/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nevhirion/multi-client
  - docker push nevhirion/multi-nginx
  - docker push nevhirion/multi-server
  - docker push nevhirion/multi-worker
